[package]
name = "repo-scraper"
version = "0.1.0"
edition = "2021"
description = "GitHub repository scraper for presenting repositories on a personal website"
repository = "https://github.com/LeHuman/repo-scraper"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.38.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.117"
secrecy = "0.8.0"
chrono = "0.4.38"
hex = "0.4.3"
bincode = "=2.0.0-rc.3"
flate2 = "1.0.30"
regex = "1.10.5"
strum = "0.26.2"
strum_macros = "0.26.4"
struct_iterable = "0.1.1"
set_field = "0.1.1"
dotenv = "0.15.0"
